apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: node:18-alpine # Oubyen l'image Docker exact dial le backend dialkom (Spring Boot, Express, Node...)
        ports:
        - containerPort: 8080 # Le port interne dial le backend dialkom
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30234 # <--- Le port public du Backend sur Azure (exactement kima f la photo) !
