export interface Project {
  id: string;
  entrepreneurId: string;
  title: string;
  description: string;
  sector: string;
  projectStatus: string;
  country: string;
  countryCode: string;
  region: string;
  keyword: string;
  founderExperienceYears: number;
  fundingRounds: number;
  teamSize: number;
  marketSizeBillion: number;
  marketGrowthRatePercent: number;
  productTractionUsers: number;
  burnRateMillion: number;
  revenueMillion: number;
  runwayMonths: number;
  founderBackground: string;
  competitionLevel: string;
  searchTrendScore: number;
  viewsWorldRank: number;
  opinions: string;
  createdAt: Date | string;
  assignedSpecialistId?: string;
  assignedSpecialist?: any;
  budget?: number;
  deadline?: string;
  category?: string;
  status?: 'active' | 'planning' | string;
  progress?: number;
  updatedAt?: string;
  priority?: string;
  tags?: string[];
  aiScores?: any;
  analysisSummary?: string;
}
